version: '3.8'

services:
  mail-categorizer:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mail-categorizer-backend
    restart: unless-stopped
    environment:
      - YAHOO_USER=${YAHOO_USER}
      - YAHOO_PASS=${YAHOO_PASS}
      - GOOGLE_USER=${GOOGLE_USER}
      - GOOGLE_PASS=${GOOGLE_PASS}
      - API_URL=http://api:8000/categorize
    volumes:
      - ./backend/logs:/app/logs
    networks:
      - mail-sentry-network
    depends_on:
      api:
        condition: service_healthy
    command: sh -c "while true; do echo 'Starting email categorization...'; python main.py; echo 'Email categorization completed. Waiting 1 hour...'; sleep 3600; done"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: mail-categorizer-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
    volumes:
      - api_data:/app/data
    networks:
      - mail-sentry-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  mail-sentry-network:
    driver: bridge

volumes:
  api_data:

