version: '3.8'

services:
  api:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
    volumes:
      - api_data:/app/data

volumes:
  api_data: